stages:
   - build
   - deploy

build_pdf:
   stage: build
   image: blang/latex
   script:
      - pdflatex -interaction nonstopmode main.tex
   artifacts:
      paths:
         - "main.pdf"
   only:
      - master

deploy_markdown:
   stage: deploy
   image:
      name: pandoc/core:2.18.0
      entrypoint: ["/bin/sh", "-c"]
   before_script:
      - 'which ssh-agent || ( apk update && apk add openssh-client git )'
      - eval $(ssh-agent -s)
      - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
      - mkdir -p ~/.ssh
      - chmod 700 ~/.ssh
      - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
      - chmod 644 ~/.ssh/known_hosts
      - git config user.email "ci@example.com"
      - git config user.name "CI"
      - git remote add ssh_origin "git@$CI_SERVER_HOST:$CI_PROJECT_PATH.git"
   script:
      - pandoc main.tex -t markdown -s -o ./main.md
      - git add "./main.md"
      - git commit -m "Compiled Markdown from $CI_COMMIT_SHORT_SHA [skip ci]"
      - git push ssh_origin HEAD:master
   only:
      - master


