stages:
  - build
  - test
  - deploy

image: blang/latex

before_script:
  - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

Build pdf:
  stage: build
  script:
    - pdflatex -interaction nonstopmode main.tex
  artifacts:
    paths:
      - "main.pdf"
  only:
    - master

Test ssh:
  stage: test
  script: 
    - ssh -v eckensso@amor.cms.hu-berlin.de
    - echo "Connected to server."
  only:
    - master

Deploy pdf:
  stage: deploy
  script:
    - rsync -atv --delete --progress main.pdf eckensso@amor.cms.hu-berlin.de
  only:
    - master

