stages:
   - deploy

build_pdf:
   stage: build
   image: blang/latex
   script:
      - pdflatex -interaction nonstopmode main.tex
   artifacts:
      paths:
         - "main.pdf"
   only:
      - master


