image: registry.gitlab.com/islandoftex/images/texlive:latest

build:
  script:
    - pdflatex main.tex
    - biber main
    - pdflatex main.tex
  after_script:
    - cat main.log
  artifacts:
    paths:
      - main.pdf

