stages:
  - build
  - test
  - deploy

image: blang/latex

before_script:
  - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

Build pdf:
  stage: build
  script:
    - pdflatex -interaction nonstopmode main.tex
  artifacts:
    paths:
      - "main.pdf"
  only:
    - master

Test ssh:
  stage: test
  script: 
    - ssh eckensso@amor.cms.hu-berlin.de -vv
    - echo "Connected to server."
  only:
    - master

Deploy pdf:
  stage: deploy
  script:
    - rsync -atv --delete --progress main.pdf eckensso@amor.cms.hu-berlin.de:/home/geschichte/eckensso
  only:
    - master

